# _config.yml
title: "El viaje del Nibelungo"
author: Bernardo
theme: minima

# Opciones adicionales (descomenta si las necesitas)
# baseurl: ""          # si usas un subdirectorio
# url: "https://tu-usuario.github.io"
